executable = /afs/cern.ch/work/m/mmolinav/public/SEG_DP_KFC/condor/bin/run_hepatic.sh
arguments = $(method) $(epsilon) $(seed) $(lr) $(optimizer)

output = /afs/cern.ch/work/m/mmolinav/public/SEG_DP_KFC/condor/output/hepatic_$(method)_eps$(epsilon)_s$(seed).$(ClusterId).$(ProcId).out
error  = /afs/cern.ch/work/m/mmolinav/public/SEG_DP_KFC/condor/error/hepatic_$(method)_eps$(epsilon)_s$(seed).$(ClusterId).$(ProcId).err
log    = /afs/cern.ch/work/m/mmolinav/public/SEG_DP_KFC/condor/log/hepatic.$(ClusterId).log

should_transfer_files = YES

MY.SendCredential = True

request_gpus = 1
requirements = regexp("A100", TARGET.GPUs_DeviceName)
request_cpus = 2
request_memory = 40GB
+JobFlavour = "tomorrow"

queue method, epsilon, seed, lr, optimizer from hepatic_jobs.txt
