executable = /afs/cern.ch/work/m/mmolinav/public/SEG_DP_KFC/condor/bin/run_hepatic_test.sh

output = /afs/cern.ch/work/m/mmolinav/public/SEG_DP_KFC/condor/output/hepatic_test.$(ClusterId).$(ProcId).out
error  = /afs/cern.ch/work/m/mmolinav/public/SEG_DP_KFC/condor/error/hepatic_test.$(ClusterId).$(ProcId).err
log    = /afs/cern.ch/work/m/mmolinav/public/SEG_DP_KFC/condor/log/hepatic_test.$(ClusterId).log

should_transfer_files = YES

MY.SendCredential = True

request_gpus = 1
requirements = regexp("A100", TARGET.GPUs_DeviceName)
request_cpus = 2
request_memory = 40GB
+JobFlavour = "espresso"

queue
